version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    target-branch: staging
    groups:
      bun:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /apps/agent
    schedule:
      interval: weekly
    target-branch: staging
    groups:
      gomod:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: staging
    groups:
      github-actions:
        patterns: ["*"]
