import { spawnSync } from "node:child_process"
import { readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import {
  si1password,
  siCaddy,
  siClaudecode,
  siCloudflare,
  siDocker,
  siGithub,
  siGo,
  siGooglechrome,
  siJetbrains,
  siMongodb,
  siMysql,
  siNeon,
  siNodedotjs,
  siOpenjdk,
  siPhp,
  siPostgresql,
  siPython,
  siRedis,
  siRuby,
  siZedindustries,
} from "simple-icons"
import { EXEMPTIONS, SOURCES } from "./logo-sources"

interface SimpleIcon {
  title: string
  hex: string
  path: string
  source: string
}

const ICONS: Record<string, SimpleIcon> = {
  "1password": si1password,
  caddy: siCaddy,
  claudecode: siClaudecode,
  cloudflare: siCloudflare,
  docker: siDocker,
  github: siGithub,
  go: siGo,
  googlechrome: siGooglechrome,
  jetbrains: siJetbrains,
  mongodb: siMongodb,
  mysql: siMysql,
  neon: siNeon,
  nodedotjs: siNodedotjs,
  openjdk: siOpenjdk,
  php: siPhp,
  postgresql: siPostgresql,
  python: siPython,
  redis: siRedis,
  ruby: siRuby,
  zedindustries: siZedindustries,
}

const PACKAGE_ROOT = path.resolve(import.meta.dir, "..")
const OUT_DIR = path.join(PACKAGE_ROOT, "src/logos")
const FORMATTER = path.join(PACKAGE_ROOT, "../../node_modules/.bin/biome")
const RETRIEVED_ON = "2026-09-04"
const LICENSE = "CC0-1.0"
const RANGE_PREFIX_RE = /^\D*/

function simpleIconsVersion(): string {
  const manifest = JSON.parse(
    readFileSync(path.join(PACKAGE_ROOT, "package.json"), "utf8")
  ) as { devDependencies: Record<string, string> }

  return manifest.devDependencies["simple-icons"].replace(RANGE_PREFIX_RE, "")
}

function format(target: string): void {
  spawnSync(FORMATTER, ["check", "--write", target], { stdio: "ignore" })
}

function iconOf(slug: string): SimpleIcon {
  const icon = ICONS[slug]

  if (!icon) {
    throw new Error(`No simple-icons entry wired for "${slug}"`)
  }

  return icon
}

function inlinable(markup: string): string {
  if (markup.includes("`") || markup.includes("${")) {
    throw new Error("Markup cannot be inlined in a template literal")
  }

  return markup
}

function fileOf(moduleId: string): string {
  return `${moduleId.replaceAll(".", "-")}.svg`
}

function svgOf(icon: SimpleIcon, monochrome: boolean): string {
  const fill = monochrome ? "currentColor" : `#${icon.hex.toLowerCase()}`

  return `<svg role="img" viewBox="0 0 24 24" fill="${fill}"><title>${icon.title}</title><path d="${icon.path}"/></svg>\n`
}

function noticeOf(rows: string[]): string {
  return `# Logos de services

Un fichier par module du catalogue qui nomme un produit de marque. Les tracés
viennent de [Simple Icons](https://simpleicons.org) ${simpleIconsVersion()},
publié sous ${LICENSE} ; la couleur de chaque fichier est la couleur de marque que
Simple Icons tient de la source citée. Les fichiers sont committés ;
\`bun scripts/generate-logos.ts\` les régénère.

**Usage nominatif.** Ces marques appartiennent à leurs titulaires. Pupitre les
affiche pour nommer un logiciel que le client installe sur son propre serveur,
ce que le droit des marques autorise. Pupitre ne s'en sert jamais pour suggérer
un partenariat, une affiliation ou un aval, ni comme icône d'action, ni en fond.

| Fichier | Module | Marque | Source | Licence du tracé | Récupéré le |
| --- | --- | --- | --- | --- | --- |
${rows.join("\n")}

## Modules sans logo

Le catalogue retombe sur une icône Lucide.

| Module | Raison |
| --- | --- |
${Object.entries(EXEMPTIONS)
  .map(([id, reason]) => `| \`${id}\` | ${reason} |`)
  .join("\n")}
`
}

function indexOf(entries: { id: string; svg: string; monochrome: boolean }[]) {
  const logos = entries
    .map(
      ({ id, svg, monochrome }) =>
        `  "${id}": {\n    svg: \`${svg}\`,\n    monochrome: ${monochrome},\n  },`
    )
    .join("\n")

  const exemptions = Object.entries(EXEMPTIONS)
    .map(([id, reason]) => `  "${id}": "${reason}",`)
    .join("\n")

  return `import type { ModuleId } from "@pupitre/shared/catalog"

export interface Logo {
  svg: string
  monochrome: boolean
}

/**
 * Generated by \`scripts/generate-logos.ts\` from the files next to this one.
 * The markup is inlined so Astro, Vite and Electron all read it the same way,
 * without a loader and without a network hop. Do not edit by hand.
 */
export const LOGOS: Readonly<Partial<Record<ModuleId, Logo>>> = {
${logos}
}

/**
 * A module with no logo, and why. An entry here is a decision, not an
 * oversight: the test refuses a catalogue module that has neither.
 */
export const EXEMPTIONS: Readonly<Partial<Record<ModuleId, string>>> = {
${exemptions}
}

export function logoFor(moduleId: ModuleId): Logo | null {
  return LOGOS[moduleId] ?? null
}
`
}

for (const entry of readdirSync(OUT_DIR)) {
  if (entry.endsWith(".svg")) {
    rmSync(path.join(OUT_DIR, entry))
  }
}

const rows: string[] = []

for (const { id, slug, monochrome } of SOURCES) {
  const icon = iconOf(slug)

  writeFileSync(path.join(OUT_DIR, fileOf(id)), svgOf(icon, monochrome))
  rows.push(
    `| \`${fileOf(id)}\` | \`${id}\` | ${icon.title} | ${icon.source} | ${LICENSE} | ${RETRIEVED_ON} |`
  )
}

writeFileSync(path.join(OUT_DIR, "NOTICE.md"), noticeOf(rows))
format(OUT_DIR)

const entries = SOURCES.map(({ id, monochrome }) => ({
  id,
  monochrome,
  svg: inlinable(readFileSync(path.join(OUT_DIR, fileOf(id)), "utf8").trim()),
}))

writeFileSync(path.join(OUT_DIR, "index.ts"), indexOf(entries))
format(path.join(OUT_DIR, "index.ts"))

process.stdout.write(
  `Wrote ${entries.length} logos, NOTICE.md and index.ts to src/logos.\n`
)
