export const en = {
  "site.name": "Pupitre",
  "a11y.skip": "Skip to content",
  "nav.label": "Main",
  "nav.docs": "Docs",
  "nav.pricing": "Pricing",
  "nav.download": "Download",
  "nav.blog": "Blog",
  "nav.cta": "Download the app",
  "theme.label": "Theme",
  "theme.system": "System",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "locale.alternateName": "Français",
  "footer.legal": "Legal",
  "footer.terms": "Terms",
  "footer.privacy": "Privacy",
  "footer.licence": "Licence",
  "footer.acceptableUse": "Acceptable use",
  "footer.company": "Pupitre LLC — legal notice to come",
  "callout.info": "Note",
  "callout.warn": "Warning",
  "callout.danger": "Danger",
} as const

export type Dictionary = Record<keyof typeof en, string>
