import type { Dictionary } from "./en"

export const fr: Dictionary = {
  "site.name": "Pupitre",
  "a11y.skip": "Aller au contenu",
  "nav.label": "Principale",
  "nav.docs": "Docs",
  "nav.pricing": "Tarifs",
  "nav.download": "Télécharger",
  "nav.blog": "Blog",
  "nav.cta": "Télécharger l’app",
  "theme.label": "Thème",
  "theme.system": "Système",
  "theme.light": "Clair",
  "theme.dark": "Sombre",
  "locale.alternateName": "English",
  "footer.legal": "Légal",
  "footer.terms": "Conditions",
  "footer.privacy": "Confidentialité",
  "footer.licence": "Licence",
  "footer.acceptableUse": "Usage acceptable",
  "footer.company": "Pupitre LLC — mentions légales à venir",
  "callout.info": "Note",
  "callout.warn": "Attention",
  "callout.danger": "Danger",
}
