/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AuthDeviceRouteImport } from './routes/auth/device'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardDevicesRouteImport } from './routes/dashboard/devices'
import { Route as DashboardDownloadRouteImport } from './routes/dashboard/download'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardOrganizationRouteImport } from './routes/dashboard/organization'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardStartRouteImport } from './routes/dashboard/start'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthInvitationIdRouteImport } from './routes/auth/invitation.$id'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAdminEventsRouteImport } from './routes/dashboard/admin/events'
import { Route as DashboardAdminReleasesRouteImport } from './routes/dashboard/admin/releases'
import { Route as DashboardAdminTeamRouteImport } from './routes/dashboard/admin/team'
import { Route as DashboardServersIndexRouteImport } from './routes/dashboard/servers/index'
import { Route as DashboardServersIdRouteImport } from './routes/dashboard/servers/$id'
import { Route as DashboardAdminAffiliateLinksIndexRouteImport } from './routes/dashboard/admin/affiliate-links/index'
import { Route as DashboardAdminAffiliateLinksIdRouteImport } from './routes/dashboard/admin/affiliate-links/$id'
import { Route as DashboardAdminInboxIndexRouteImport } from './routes/dashboard/admin/inbox/index'
import { Route as DashboardAdminInboxThreadIdRouteImport } from './routes/dashboard/admin/inbox/$threadId'
import { Route as DashboardAdminOrganizationsIndexRouteImport } from './routes/dashboard/admin/organizations/index'
import { Route as DashboardAdminOrganizationsIdRouteImport } from './routes/dashboard/admin/organizations/$id'
import { Route as DashboardAdminServersIndexRouteImport } from './routes/dashboard/admin/servers/index'
import { Route as DashboardAdminServersIdRouteImport } from './routes/dashboard/admin/servers/$id'
import { Route as DashboardAdminSubscriptionsIndexRouteImport } from './routes/dashboard/admin/subscriptions/index'
import { Route as DashboardAdminSubscriptionsIdRouteImport } from './routes/dashboard/admin/subscriptions/$id'
import { Route as DashboardAdminUsersIndexRouteImport } from './routes/dashboard/admin/users/index'
import { Route as DashboardAdminUsersIdRouteImport } from './routes/dashboard/admin/users/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDownloadRoute = DashboardDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationRoute = DashboardOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStartRoute = DashboardStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInvitationIdRoute = AuthInvitationIdRouteImport.update({
  id: '/auth/invitation/$id',
  path: '/auth/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminEventsRoute = DashboardAdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminReleasesRoute = DashboardAdminReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTeamRoute = DashboardAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardServersIndexRoute = DashboardServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServersIdRoute = DashboardServersIdRouteImport.update({
  id: '/servers/$id',
  path: '/servers/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminAffiliateLinksIndexRoute =
  DashboardAdminAffiliateLinksIndexRouteImport.update({
    id: '/affiliate-links/',
    path: '/affiliate-links/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminAffiliateLinksIdRoute =
  DashboardAdminAffiliateLinksIdRouteImport.update({
    id: '/affiliate-links/$id',
    path: '/affiliate-links/$id',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminInboxIndexRoute =
  DashboardAdminInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminInboxThreadIdRoute =
  DashboardAdminInboxThreadIdRouteImport.update({
    id: '/inbox/$threadId',
    path: '/inbox/$threadId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminOrganizationsIndexRoute =
  DashboardAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminOrganizationsIdRoute =
  DashboardAdminOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminServersIndexRoute =
  DashboardAdminServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminServersIdRoute = DashboardAdminServersIdRouteImport.update({
  id: '/servers/$id',
  path: '/servers/$id',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSubscriptionsIndexRoute =
  DashboardAdminSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminSubscriptionsIdRoute =
  DashboardAdminSubscriptionsIdRouteImport.update({
    id: '/subscriptions/$id',
    path: '/subscriptions/$id',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminUsersIndexRoute =
  DashboardAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminUsersIdRoute = DashboardAdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/status': typeof StatusRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/start': typeof DashboardStartRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/invitation/$id': typeof AuthInvitationIdRoute
  '/dashboard/admin/events': typeof DashboardAdminEventsRoute
  '/dashboard/admin/releases': typeof DashboardAdminReleasesRoute
  '/dashboard/admin/team': typeof DashboardAdminTeamRoute
  '/dashboard/servers/$id': typeof DashboardServersIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/servers/': typeof DashboardServersIndexRoute
  '/dashboard/admin/affiliate-links/$id': typeof DashboardAdminAffiliateLinksIdRoute
  '/dashboard/admin/inbox/$threadId': typeof DashboardAdminInboxThreadIdRoute
  '/dashboard/admin/organizations/$id': typeof DashboardAdminOrganizationsIdRoute
  '/dashboard/admin/servers/$id': typeof DashboardAdminServersIdRoute
  '/dashboard/admin/subscriptions/$id': typeof DashboardAdminSubscriptionsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/admin/affiliate-links/': typeof DashboardAdminAffiliateLinksIndexRoute
  '/dashboard/admin/inbox/': typeof DashboardAdminInboxIndexRoute
  '/dashboard/admin/organizations/': typeof DashboardAdminOrganizationsIndexRoute
  '/dashboard/admin/servers/': typeof DashboardAdminServersIndexRoute
  '/dashboard/admin/subscriptions/': typeof DashboardAdminSubscriptionsIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/status': typeof StatusRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/start': typeof DashboardStartRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/invitation/$id': typeof AuthInvitationIdRoute
  '/dashboard/admin/events': typeof DashboardAdminEventsRoute
  '/dashboard/admin/releases': typeof DashboardAdminReleasesRoute
  '/dashboard/admin/team': typeof DashboardAdminTeamRoute
  '/dashboard/servers/$id': typeof DashboardServersIdRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/servers': typeof DashboardServersIndexRoute
  '/dashboard/admin/affiliate-links/$id': typeof DashboardAdminAffiliateLinksIdRoute
  '/dashboard/admin/inbox/$threadId': typeof DashboardAdminInboxThreadIdRoute
  '/dashboard/admin/organizations/$id': typeof DashboardAdminOrganizationsIdRoute
  '/dashboard/admin/servers/$id': typeof DashboardAdminServersIdRoute
  '/dashboard/admin/subscriptions/$id': typeof DashboardAdminSubscriptionsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/admin/affiliate-links': typeof DashboardAdminAffiliateLinksIndexRoute
  '/dashboard/admin/inbox': typeof DashboardAdminInboxIndexRoute
  '/dashboard/admin/organizations': typeof DashboardAdminOrganizationsIndexRoute
  '/dashboard/admin/servers': typeof DashboardAdminServersIndexRoute
  '/dashboard/admin/subscriptions': typeof DashboardAdminSubscriptionsIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/status': typeof StatusRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/start': typeof DashboardStartRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/invitation/$id': typeof AuthInvitationIdRoute
  '/dashboard/admin/events': typeof DashboardAdminEventsRoute
  '/dashboard/admin/releases': typeof DashboardAdminReleasesRoute
  '/dashboard/admin/team': typeof DashboardAdminTeamRoute
  '/dashboard/servers/$id': typeof DashboardServersIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/servers/': typeof DashboardServersIndexRoute
  '/dashboard/admin/affiliate-links/$id': typeof DashboardAdminAffiliateLinksIdRoute
  '/dashboard/admin/inbox/$threadId': typeof DashboardAdminInboxThreadIdRoute
  '/dashboard/admin/organizations/$id': typeof DashboardAdminOrganizationsIdRoute
  '/dashboard/admin/servers/$id': typeof DashboardAdminServersIdRoute
  '/dashboard/admin/subscriptions/$id': typeof DashboardAdminSubscriptionsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/admin/affiliate-links/': typeof DashboardAdminAffiliateLinksIndexRoute
  '/dashboard/admin/inbox/': typeof DashboardAdminInboxIndexRoute
  '/dashboard/admin/organizations/': typeof DashboardAdminOrganizationsIndexRoute
  '/dashboard/admin/servers/': typeof DashboardAdminServersIndexRoute
  '/dashboard/admin/subscriptions/': typeof DashboardAdminSubscriptionsIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/download'
    | '/status'
    | '/auth/device'
    | '/auth/sign-in'
    | '/auth/two-factor'
    | '/dashboard/admin'
    | '/dashboard/audit'
    | '/dashboard/billing'
    | '/dashboard/devices'
    | '/dashboard/download'
    | '/dashboard/members'
    | '/dashboard/organization'
    | '/dashboard/settings'
    | '/dashboard/start'
    | '/dashboard/'
    | '/api/auth/$'
    | '/auth/invitation/$id'
    | '/dashboard/admin/events'
    | '/dashboard/admin/releases'
    | '/dashboard/admin/team'
    | '/dashboard/servers/$id'
    | '/dashboard/admin/'
    | '/dashboard/servers/'
    | '/dashboard/admin/affiliate-links/$id'
    | '/dashboard/admin/inbox/$threadId'
    | '/dashboard/admin/organizations/$id'
    | '/dashboard/admin/servers/$id'
    | '/dashboard/admin/subscriptions/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/admin/affiliate-links/'
    | '/dashboard/admin/inbox/'
    | '/dashboard/admin/organizations/'
    | '/dashboard/admin/servers/'
    | '/dashboard/admin/subscriptions/'
    | '/dashboard/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/status'
    | '/auth/device'
    | '/auth/sign-in'
    | '/auth/two-factor'
    | '/dashboard/audit'
    | '/dashboard/billing'
    | '/dashboard/devices'
    | '/dashboard/download'
    | '/dashboard/members'
    | '/dashboard/organization'
    | '/dashboard/settings'
    | '/dashboard/start'
    | '/dashboard'
    | '/api/auth/$'
    | '/auth/invitation/$id'
    | '/dashboard/admin/events'
    | '/dashboard/admin/releases'
    | '/dashboard/admin/team'
    | '/dashboard/servers/$id'
    | '/dashboard/admin'
    | '/dashboard/servers'
    | '/dashboard/admin/affiliate-links/$id'
    | '/dashboard/admin/inbox/$threadId'
    | '/dashboard/admin/organizations/$id'
    | '/dashboard/admin/servers/$id'
    | '/dashboard/admin/subscriptions/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/admin/affiliate-links'
    | '/dashboard/admin/inbox'
    | '/dashboard/admin/organizations'
    | '/dashboard/admin/servers'
    | '/dashboard/admin/subscriptions'
    | '/dashboard/admin/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/download'
    | '/status'
    | '/auth/device'
    | '/auth/sign-in'
    | '/auth/two-factor'
    | '/dashboard/admin'
    | '/dashboard/audit'
    | '/dashboard/billing'
    | '/dashboard/devices'
    | '/dashboard/download'
    | '/dashboard/members'
    | '/dashboard/organization'
    | '/dashboard/settings'
    | '/dashboard/start'
    | '/dashboard/'
    | '/api/auth/$'
    | '/auth/invitation/$id'
    | '/dashboard/admin/events'
    | '/dashboard/admin/releases'
    | '/dashboard/admin/team'
    | '/dashboard/servers/$id'
    | '/dashboard/admin/'
    | '/dashboard/servers/'
    | '/dashboard/admin/affiliate-links/$id'
    | '/dashboard/admin/inbox/$threadId'
    | '/dashboard/admin/organizations/$id'
    | '/dashboard/admin/servers/$id'
    | '/dashboard/admin/subscriptions/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/admin/affiliate-links/'
    | '/dashboard/admin/inbox/'
    | '/dashboard/admin/organizations/'
    | '/dashboard/admin/servers/'
    | '/dashboard/admin/subscriptions/'
    | '/dashboard/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  StatusRoute: typeof StatusRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthInvitationIdRoute: typeof AuthInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/download': {
      id: '/dashboard/download'
      path: '/download'
      fullPath: '/dashboard/download'
      preLoaderRoute: typeof DashboardDownloadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/organization': {
      id: '/dashboard/organization'
      path: '/organization'
      fullPath: '/dashboard/organization'
      preLoaderRoute: typeof DashboardOrganizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/start': {
      id: '/dashboard/start'
      path: '/start'
      fullPath: '/dashboard/start'
      preLoaderRoute: typeof DashboardStartRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invitation/$id': {
      id: '/auth/invitation/$id'
      path: '/auth/invitation/$id'
      fullPath: '/auth/invitation/$id'
      preLoaderRoute: typeof AuthInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/events': {
      id: '/dashboard/admin/events'
      path: '/events'
      fullPath: '/dashboard/admin/events'
      preLoaderRoute: typeof DashboardAdminEventsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/releases': {
      id: '/dashboard/admin/releases'
      path: '/releases'
      fullPath: '/dashboard/admin/releases'
      preLoaderRoute: typeof DashboardAdminReleasesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/team': {
      id: '/dashboard/admin/team'
      path: '/team'
      fullPath: '/dashboard/admin/team'
      preLoaderRoute: typeof DashboardAdminTeamRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/servers/': {
      id: '/dashboard/servers/'
      path: '/servers'
      fullPath: '/dashboard/servers/'
      preLoaderRoute: typeof DashboardServersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servers/$id': {
      id: '/dashboard/servers/$id'
      path: '/servers/$id'
      fullPath: '/dashboard/servers/$id'
      preLoaderRoute: typeof DashboardServersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/affiliate-links/': {
      id: '/dashboard/admin/affiliate-links/'
      path: '/affiliate-links'
      fullPath: '/dashboard/admin/affiliate-links/'
      preLoaderRoute: typeof DashboardAdminAffiliateLinksIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/affiliate-links/$id': {
      id: '/dashboard/admin/affiliate-links/$id'
      path: '/affiliate-links/$id'
      fullPath: '/dashboard/admin/affiliate-links/$id'
      preLoaderRoute: typeof DashboardAdminAffiliateLinksIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/inbox/': {
      id: '/dashboard/admin/inbox/'
      path: '/inbox'
      fullPath: '/dashboard/admin/inbox/'
      preLoaderRoute: typeof DashboardAdminInboxIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/inbox/$threadId': {
      id: '/dashboard/admin/inbox/$threadId'
      path: '/inbox/$threadId'
      fullPath: '/dashboard/admin/inbox/$threadId'
      preLoaderRoute: typeof DashboardAdminInboxThreadIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/organizations/': {
      id: '/dashboard/admin/organizations/'
      path: '/organizations'
      fullPath: '/dashboard/admin/organizations/'
      preLoaderRoute: typeof DashboardAdminOrganizationsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/organizations/$id': {
      id: '/dashboard/admin/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/dashboard/admin/organizations/$id'
      preLoaderRoute: typeof DashboardAdminOrganizationsIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/servers/': {
      id: '/dashboard/admin/servers/'
      path: '/servers'
      fullPath: '/dashboard/admin/servers/'
      preLoaderRoute: typeof DashboardAdminServersIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/servers/$id': {
      id: '/dashboard/admin/servers/$id'
      path: '/servers/$id'
      fullPath: '/dashboard/admin/servers/$id'
      preLoaderRoute: typeof DashboardAdminServersIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/subscriptions/': {
      id: '/dashboard/admin/subscriptions/'
      path: '/subscriptions'
      fullPath: '/dashboard/admin/subscriptions/'
      preLoaderRoute: typeof DashboardAdminSubscriptionsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/subscriptions/$id': {
      id: '/dashboard/admin/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/dashboard/admin/subscriptions/$id'
      preLoaderRoute: typeof DashboardAdminSubscriptionsIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/users/': {
      id: '/dashboard/admin/users/'
      path: '/users'
      fullPath: '/dashboard/admin/users/'
      preLoaderRoute: typeof DashboardAdminUsersIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/users/$id': {
      id: '/dashboard/admin/users/$id'
      path: '/users/$id'
      fullPath: '/dashboard/admin/users/$id'
      preLoaderRoute: typeof DashboardAdminUsersIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminEventsRoute: typeof DashboardAdminEventsRoute
  DashboardAdminReleasesRoute: typeof DashboardAdminReleasesRoute
  DashboardAdminTeamRoute: typeof DashboardAdminTeamRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminAffiliateLinksIdRoute: typeof DashboardAdminAffiliateLinksIdRoute
  DashboardAdminInboxThreadIdRoute: typeof DashboardAdminInboxThreadIdRoute
  DashboardAdminOrganizationsIdRoute: typeof DashboardAdminOrganizationsIdRoute
  DashboardAdminServersIdRoute: typeof DashboardAdminServersIdRoute
  DashboardAdminSubscriptionsIdRoute: typeof DashboardAdminSubscriptionsIdRoute
  DashboardAdminUsersIdRoute: typeof DashboardAdminUsersIdRoute
  DashboardAdminAffiliateLinksIndexRoute: typeof DashboardAdminAffiliateLinksIndexRoute
  DashboardAdminInboxIndexRoute: typeof DashboardAdminInboxIndexRoute
  DashboardAdminOrganizationsIndexRoute: typeof DashboardAdminOrganizationsIndexRoute
  DashboardAdminServersIndexRoute: typeof DashboardAdminServersIndexRoute
  DashboardAdminSubscriptionsIndexRoute: typeof DashboardAdminSubscriptionsIndexRoute
  DashboardAdminUsersIndexRoute: typeof DashboardAdminUsersIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminEventsRoute: DashboardAdminEventsRoute,
  DashboardAdminReleasesRoute: DashboardAdminReleasesRoute,
  DashboardAdminTeamRoute: DashboardAdminTeamRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminAffiliateLinksIdRoute: DashboardAdminAffiliateLinksIdRoute,
  DashboardAdminInboxThreadIdRoute: DashboardAdminInboxThreadIdRoute,
  DashboardAdminOrganizationsIdRoute: DashboardAdminOrganizationsIdRoute,
  DashboardAdminServersIdRoute: DashboardAdminServersIdRoute,
  DashboardAdminSubscriptionsIdRoute: DashboardAdminSubscriptionsIdRoute,
  DashboardAdminUsersIdRoute: DashboardAdminUsersIdRoute,
  DashboardAdminAffiliateLinksIndexRoute:
    DashboardAdminAffiliateLinksIndexRoute,
  DashboardAdminInboxIndexRoute: DashboardAdminInboxIndexRoute,
  DashboardAdminOrganizationsIndexRoute: DashboardAdminOrganizationsIndexRoute,
  DashboardAdminServersIndexRoute: DashboardAdminServersIndexRoute,
  DashboardAdminSubscriptionsIndexRoute: DashboardAdminSubscriptionsIndexRoute,
  DashboardAdminUsersIndexRoute: DashboardAdminUsersIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardDownloadRoute: typeof DashboardDownloadRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardOrganizationRoute: typeof DashboardOrganizationRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStartRoute: typeof DashboardStartRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardServersIdRoute: typeof DashboardServersIdRoute
  DashboardServersIndexRoute: typeof DashboardServersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardDownloadRoute: DashboardDownloadRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardOrganizationRoute: DashboardOrganizationRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStartRoute: DashboardStartRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardServersIdRoute: DashboardServersIdRoute,
  DashboardServersIndexRoute: DashboardServersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DownloadRoute: DownloadRoute,
  StatusRoute: StatusRoute,
  AuthDeviceRoute: AuthDeviceRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthInvitationIdRoute: AuthInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
