package caddy

import (
	"fmt"
	"strings"

	"pupitre.studio/agent/internal/modules/exposure/routes"
	"pupitre.studio/agent/internal/registry"
)

// Rewriting Host defeats a dev server's allowedHosts check without touching its vite.config.ts.
func caddyfile(email string, httpPort, httpsPort int, published []routes.Route) []byte {
	var out strings.Builder

	fmt.Fprintf(&out, "# Generated by pupitred — source: %s\n", registry.DefaultConf)
	out.WriteString("{\n")
	if email != "" {
		fmt.Fprintf(&out, "\temail %s\n", email)
	}
	fmt.Fprintf(&out, "\thttp_port %d\n", httpPort)
	fmt.Fprintf(&out, "\thttps_port %d\n", httpsPort)
	out.WriteString("}\n")

	for _, route := range published {
		origin := strings.TrimPrefix(route.Service, "http://")

		fmt.Fprintf(&out, "\n# %s\n", route.Project)
		fmt.Fprintf(&out, "%s {\n", route.Hostname)
		fmt.Fprintf(&out, "\treverse_proxy %s {\n", origin)
		fmt.Fprintf(&out, "\t\theader_up Host %s\n", origin)
		out.WriteString("\t}\n}\n")
	}

	return []byte(out.String())
}
