package caddy

import (
	"fmt"
	"strings"

	"pupitre.studio/agent/internal/gate"
	"pupitre.studio/agent/internal/modules/exposure/routes"
	"pupitre.studio/agent/internal/registry"
)

// Every name goes to the gate with its Host untouched: the gate picks the route by it, then sends the origin's own.
func caddyfile(email string, httpPort, httpsPort int, published []routes.Route) []byte {
	var out strings.Builder

	fmt.Fprintf(&out, "# Generated by pupitred — source: %s\n", registry.DefaultConf)
	out.WriteString("{\n")
	if email != "" {
		fmt.Fprintf(&out, "\temail %s\n", email)
	}
	fmt.Fprintf(&out, "\thttp_port %d\n", httpPort)
	fmt.Fprintf(&out, "\thttps_port %d\n", httpsPort)
	out.WriteString("}\n")

	for _, route := range published {
		fmt.Fprintf(&out, "\n# %s\n", route.Project)
		fmt.Fprintf(&out, "%s {\n", route.Hostname)
		fmt.Fprintf(&out, "\treverse_proxy %s\n", gate.Address)
		out.WriteString("}\n")
	}

	return []byte(out.String())
}
