import type { DictionaryKey } from "@/lib/i18n/en"

export const AUDIT_ACTIONS = [
  "server.enrolled",
  "server.exchanged",
  "server.assigned",
  "server.unassigned",
  "server.device_revoked",
  "server.deleted",
  "device.added",
  "device.revoked",
  "member.invited",
  "subscription.created",
  "subscription.updated",
  "subscription.canceled",
  "subscription.granted",
  "subscription.deleted",
  "referral.recorded",
  "affiliate_link.created",
  "affiliate_link.updated",
  "affiliate_link.deleted",
  "user.banned",
  "user.unbanned",
  "user.deactivated",
  "user.reactivated",
  "user.deleted",
  "user.purged",
  "user.purge_skipped",
  "user.sessions_revoked",
  "organization.suspended",
  "organization.restored",
  "organization.closed",
  "organization.reopened",
  "organization.deleted",
  "organization.purged",
  "organization.updated",
  "organization.transferred",
  "server.restored",
  "server.updated",
  "server.alerts_cleared",
  "backup.created",
  "backup.deleted",
  "backup.forgotten",
  "backup.restored",
  "mail.replied",
  "mail.composed",
  "mail.closed",
  "mail.reopened",
  "mail.assigned",
  "mail.read",
  "mail.attachment_read",
  "mail.linked",
  "mail.note_added",
  "mail.note_deleted",
  "mail.bulk_closed",
  "mail.bulk_reopened",
  "mail.bulk_read",
  "mail.bulk_unread",
  "mail.mailbox_created",
  "mail.mailbox_updated",
  "mail.mailbox_deleted",
  "mail.template_created",
  "mail.template_updated",
  "mail.template_deleted",
] as const

export type AuditAction = (typeof AUDIT_ACTIONS)[number]

const ACTION_KEYS: Record<AuditAction, DictionaryKey> = {
  "server.enrolled": "audit.action.server.enrolled",
  "server.exchanged": "audit.action.server.exchanged",
  "server.assigned": "audit.action.server.assigned",
  "server.unassigned": "audit.action.server.unassigned",
  "server.device_revoked": "audit.action.server.device_revoked",
  "server.deleted": "audit.action.server.deleted",
  "device.added": "audit.action.device.added",
  "device.revoked": "audit.action.device.revoked",
  "member.invited": "audit.action.member.invited",
  "subscription.created": "audit.action.subscription.created",
  "subscription.updated": "audit.action.subscription.updated",
  "subscription.canceled": "audit.action.subscription.canceled",
  "subscription.granted": "audit.action.subscription.granted",
  "subscription.deleted": "audit.action.subscription.deleted",
  "referral.recorded": "audit.action.referral.recorded",
  "affiliate_link.created": "audit.action.affiliate_link.created",
  "affiliate_link.updated": "audit.action.affiliate_link.updated",
  "affiliate_link.deleted": "audit.action.affiliate_link.deleted",
  "user.banned": "audit.action.user.banned",
  "user.unbanned": "audit.action.user.unbanned",
  "user.deactivated": "audit.action.user.deactivated",
  "user.reactivated": "audit.action.user.reactivated",
  "user.deleted": "audit.action.user.deleted",
  "user.purged": "audit.action.user.purged",
  "user.purge_skipped": "audit.action.user.purge_skipped",
  "user.sessions_revoked": "audit.action.user.sessions_revoked",
  "organization.suspended": "audit.action.organization.suspended",
  "organization.restored": "audit.action.organization.restored",
  "organization.closed": "audit.action.organization.closed",
  "organization.reopened": "audit.action.organization.reopened",
  "organization.deleted": "audit.action.organization.deleted",
  "organization.purged": "audit.action.organization.purged",
  "organization.updated": "audit.action.organization.updated",
  "organization.transferred": "audit.action.organization.transferred",
  "server.restored": "audit.action.server.restored",
  "server.updated": "audit.action.server.updated",
  "server.alerts_cleared": "audit.action.server.alerts_cleared",
  "backup.created": "audit.action.backup.created",
  "backup.deleted": "audit.action.backup.deleted",
  "backup.forgotten": "audit.action.backup.forgotten",
  "backup.restored": "audit.action.backup.restored",
  "mail.replied": "audit.action.mail.replied",
  "mail.composed": "audit.action.mail.composed",
  "mail.closed": "audit.action.mail.closed",
  "mail.reopened": "audit.action.mail.reopened",
  "mail.assigned": "audit.action.mail.assigned",
  "mail.read": "audit.action.mail.read",
  "mail.attachment_read": "audit.action.mail.attachment_read",
  "mail.linked": "audit.action.mail.linked",
  "mail.note_added": "audit.action.mail.note_added",
  "mail.note_deleted": "audit.action.mail.note_deleted",
  "mail.bulk_closed": "audit.action.mail.bulk_closed",
  "mail.bulk_reopened": "audit.action.mail.bulk_reopened",
  "mail.bulk_read": "audit.action.mail.bulk_read",
  "mail.bulk_unread": "audit.action.mail.bulk_unread",
  "mail.mailbox_created": "audit.action.mail.mailbox_created",
  "mail.mailbox_updated": "audit.action.mail.mailbox_updated",
  "mail.mailbox_deleted": "audit.action.mail.mailbox_deleted",
  "mail.template_created": "audit.action.mail.template_created",
  "mail.template_updated": "audit.action.mail.template_updated",
  "mail.template_deleted": "audit.action.mail.template_deleted",
}

export const AUDIT_TARGET_TYPES = [
  "server",
  "backup",
  "device",
  "invitation",
  "subscription",
  "release",
  "affiliate_link",
  "user",
  "organization",
  "mail_thread",
  "mail_mailbox",
  "mail_template",
] as const

const TARGET_KEYS: Record<string, DictionaryKey> = {
  server: "audit.target.server",
  backup: "audit.target.backup",
  device: "audit.target.device",
  invitation: "audit.target.invitation",
  subscription: "audit.target.subscription",
  release: "audit.target.release",
  affiliate_link: "audit.target.affiliate_link",
  user: "audit.target.user",
  organization: "audit.target.organization",
  mail_thread: "audit.target.mail_thread",
  mail_mailbox: "audit.target.mail_mailbox",
  mail_template: "audit.target.mail_template",
}

/** A key when the action is one we name, and the raw action when it is not. */
export function actionKey(action: string): DictionaryKey | null {
  return ACTION_KEYS[action as AuditAction] ?? null
}

export function targetKey(targetType: string): DictionaryKey | null {
  return TARGET_KEYS[targetType] ?? null
}

export const EVENTS_PER_PAGE = 25
