import { afterEach, describe, expect, test } from "bun:test"
import { spawnSync } from "node:child_process"
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import {
  checkPrismaClientFreshness,
  computeFingerprint,
  STAMP_FILE,
} from "../check-prisma-client-freshness"

const SCRIPT = path.resolve(
  import.meta.dir,
  "../check-prisma-client-freshness.ts"
)

const SCHEMA = [
  "generator client {",
  '  provider = "prisma-client"',
  '  runtime  = "bun"',
  '  output   = "../src/generated/prisma"',
  "}",
  "",
  "datasource db {",
  '  provider = "postgresql"',
  "}",
  "",
  "model Server {",
  "  id   String @id",
  "  name String",
  "}",
  "",
].join("\n")

const VERSION = "7.10.0"

const dirs: string[] = []

function write(file: string, content: string): void {
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, content)
}

function generatedClass(schema: string, version: string): string {
  return [
    "const config = {",
    `  "clientVersion": ${JSON.stringify(version)},`,
    `  "inlineSchema": ${JSON.stringify(schema)},`,
    "}",
    "",
  ].join("\n")
}

interface TFixtureOptions {
  schema?: string
  embeddedSchema?: string
  embeddedVersion?: string
  installedVersion?: string
  stamp?: boolean
  clients?: string[]
}

function fixture(options: TFixtureOptions = {}): string {
  const dir = mkdtempSync(path.join(tmpdir(), "pupitre-prisma-fresh-"))
  dirs.push(dir)

  const schema = options.schema ?? SCHEMA
  const embeddedSchema = options.embeddedSchema ?? schema
  const embeddedVersion = options.embeddedVersion ?? VERSION
  const installedVersion = options.installedVersion ?? VERSION
  const clients = options.clients ?? [
    "src/generated/prisma",
    "src/generated/prisma-cloudflare",
  ]

  write(path.join(dir, "prisma/schema.prisma"), schema)
  write(
    path.join(dir, "package.json"),
    JSON.stringify({
      dependencies: { "@prisma/client": `^${VERSION}` },
      devDependencies: { prisma: `^${VERSION}` },
    })
  )
  write(
    path.join(dir, "node_modules/@prisma/client/package.json"),
    JSON.stringify({ version: installedVersion })
  )

  for (const client of clients) {
    write(
      path.join(dir, client, "internal/class.ts"),
      generatedClass(embeddedSchema, embeddedVersion)
    )
  }

  if (options.stamp !== false) {
    write(
      path.join(dir, "src/generated", STAMP_FILE),
      `${computeFingerprint(dir)}\n`
    )
  }

  return dir
}

afterEach(() => {
  for (const dir of dirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true })
  }
})

describe("fingerprint", () => {
  test("ignores reformatting of the schema", () => {
    const compact = fixture()
    const reformatted = fixture({
      schema: SCHEMA.replace("  id   String @id", "  id String   @id"),
    })

    expect(computeFingerprint(compact)).toBe(computeFingerprint(reformatted))
  })

  test("changes with the schema", () => {
    const before = fixture()
    const after = fixture({
      schema: SCHEMA.replace("  name String", "  name String\n  host String"),
    })

    expect(computeFingerprint(before)).not.toBe(computeFingerprint(after))
  })

  test("changes with the declared Prisma version", () => {
    const dir = fixture()
    const before = computeFingerprint(dir)

    writeFileSync(
      path.join(dir, "package.json"),
      JSON.stringify({
        dependencies: { "@prisma/client": "^7.11.0" },
        devDependencies: { prisma: "^7.11.0" },
      })
    )

    expect(computeFingerprint(dir)).not.toBe(before)
  })
})

describe("a fresh tree passes", () => {
  test("no failure when clients, versions and stamp agree", () => {
    const result = checkPrismaClientFreshness(fixture())

    expect(result.failures).toEqual([])
  })
})

describe("a stale tree is refused", () => {
  test("schema edited without regenerating", () => {
    const dir = fixture()
    writeFileSync(
      path.join(dir, "prisma/schema.prisma"),
      SCHEMA.replace("  name String", "  name String\n  host String")
    )

    const { failures } = checkPrismaClientFreshness(dir)

    expect(failures).toEqual([
      "packages/db/src/generated/prisma was generated from a different schema than packages/db/prisma/schema.prisma.",
      "packages/db/src/generated/prisma-cloudflare was generated from a different schema than packages/db/prisma/schema.prisma.",
    ])
  })

  test("client generated by another Prisma version", () => {
    const { failures } = checkPrismaClientFreshness(
      fixture({ embeddedVersion: "7.9.1" })
    )

    expect(failures).toEqual([
      "packages/db/src/generated/prisma was generated by Prisma 7.9.1, but 7.10.0 is installed.",
      "packages/db/src/generated/prisma-cloudflare was generated by Prisma 7.9.1, but 7.10.0 is installed.",
    ])
  })

  test("a missing client", () => {
    const { failures } = checkPrismaClientFreshness(
      fixture({ clients: ["src/generated/prisma"] })
    )

    expect(failures).toEqual([
      "packages/db/src/generated/prisma-cloudflare is missing or unreadable — the committed Prisma client is not there.",
    ])
  })

  test("a missing stamp", () => {
    const { failures } = checkPrismaClientFreshness(fixture({ stamp: false }))

    expect(failures).toEqual([
      `packages/db/src/generated/${STAMP_FILE} is missing.`,
    ])
  })
})

describe("--write", () => {
  test("stamps the current inputs, after which the check passes", () => {
    const dir = fixture({ stamp: false })
    const stampPath = path.join(dir, "src/generated", STAMP_FILE)

    const written = checkPrismaClientFreshness(dir, { write: true })

    expect(written.failures).toEqual([])
    expect(existsSync(stampPath)).toBe(true)
    expect(readFileSync(stampPath, "utf8").trim()).toBe(computeFingerprint(dir))
    expect(checkPrismaClientFreshness(dir).failures).toEqual([])
  })

  test("refuses to stamp a stale client", () => {
    const dir = fixture({ embeddedVersion: "7.9.1", stamp: false })

    const { failures } = checkPrismaClientFreshness(dir, { write: true })

    expect(failures.length).toBeGreaterThan(0)
    expect(existsSync(path.join(dir, "src/generated", STAMP_FILE))).toBe(false)
  })
})

describe("command line", () => {
  test("exits 0 on a fresh fixture", () => {
    const result = spawnSync("bun", [SCRIPT, "--db-dir", fixture()], {
      encoding: "utf8",
    })

    expect(result.status).toBe(0)
    expect(result.stdout).toContain("up to date")
  })

  test("exits 1 and explains how to regenerate on a stale fixture", () => {
    const dir = fixture()
    writeFileSync(
      path.join(dir, "prisma/schema.prisma"),
      SCHEMA.replace("  name String", "  name String\n  host String")
    )

    const result = spawnSync("bun", [SCRIPT, "--db-dir", dir], {
      encoding: "utf8",
    })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain("different schema")
    expect(result.stderr).toContain("bun run db:generate")
  })
})
