import { createHash } from "node:crypto"
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join, relative } from "node:path"

const ROOT = join(import.meta.dir, "..")
const DEFAULT_DB_DIR = join(ROOT, "packages/db")

export const STAMP_FILE = ".prisma-inputs.sha256"

const GENERATED_CLIENTS = [
  "src/generated/prisma",
  "src/generated/prisma-cloudflare",
] as const

const WHITESPACE_RUN_RE = /\s+/g
const INLINE_SCHEMA_RE = /"inlineSchema":\s*("(?:[^"\\]|\\.)*")/
const CLIENT_VERSION_RE = /"clientVersion":\s*"([^"]+)"/

const REGENERATE_HINT =
  "Run `bun run db:generate && bun run check:prisma-client -- --write`, then commit the regenerated client and the stamp."

export interface TFreshnessResult {
  failures: string[]
  fingerprint: string
}

// Prisma re-indents the schema before embedding it, so only intra-line whitespace is ignored.
function normalizeSchema(source: string): string {
  return source
    .split("\n")
    .map((line) => line.trim().replace(WHITESPACE_RUN_RE, " "))
    .filter((line) => line.length > 0)
    .join("\n")
}

function sha256(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex")
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T
}

function label(relativePath: string): string {
  return `packages/db/${relativePath}`
}

function readSchema(dbDir: string): string {
  return normalizeSchema(
    readFileSync(join(dbDir, "prisma/schema.prisma"), "utf8")
  )
}

function readDeclaredVersions(dbDir: string): {
  client: string
  generator: string
} {
  const manifest = readJson<{
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }>(join(dbDir, "package.json"))

  const client = manifest.dependencies?.["@prisma/client"]
  const generator = manifest.devDependencies?.prisma

  if (!(client && generator)) {
    throw new Error(
      "packages/db/package.json declares no `prisma` / `@prisma/client` version."
    )
  }

  return { client, generator }
}

export function computeFingerprint(dbDir: string = DEFAULT_DB_DIR): string {
  const versions = readDeclaredVersions(dbDir)

  return sha256(
    [
      `schema.prisma=${sha256(readSchema(dbDir))}`,
      `prisma=${versions.generator}`,
      `@prisma/client=${versions.client}`,
    ].join("\n")
  )
}

function readEmbeddedConfig(
  dbDir: string,
  relativePath: string
): { schema: string; version: string } | null {
  const path = join(dbDir, relativePath, "internal/class.ts")

  if (!existsSync(path)) {
    return null
  }

  const source = readFileSync(path, "utf8")
  const schema = source.match(INLINE_SCHEMA_RE)
  const version = source.match(CLIENT_VERSION_RE)

  if (!(schema?.[1] && version?.[1])) {
    return null
  }

  return {
    schema: JSON.parse(schema[1]) as string,
    version: version[1],
  }
}

function installedClientVersion(dbDir: string): string | null {
  const candidates = [
    join(dbDir, "node_modules/@prisma/client/package.json"),
    join(dbDir, "../../node_modules/@prisma/client/package.json"),
  ]
  const path = candidates.find((candidate) => existsSync(candidate))

  if (!path) {
    return null
  }

  return readJson<{ version?: string }>(path).version ?? null
}

function collectClientFailures(dbDir: string): string[] {
  const failures: string[] = []
  const schema = readSchema(dbDir)
  const installed = installedClientVersion(dbDir)

  for (const relativePath of GENERATED_CLIENTS) {
    const embedded = readEmbeddedConfig(dbDir, relativePath)

    if (!embedded) {
      failures.push(
        `${label(relativePath)} is missing or unreadable — the committed Prisma client is not there.`
      )
      continue
    }

    if (normalizeSchema(embedded.schema) !== schema) {
      failures.push(
        `${label(relativePath)} was generated from a different schema than packages/db/prisma/schema.prisma.`
      )
    }

    if (installed && embedded.version !== installed) {
      failures.push(
        `${label(relativePath)} was generated by Prisma ${embedded.version}, but ${installed} is installed.`
      )
    }
  }

  return failures
}

function collectStampFailures(dbDir: string, fingerprint: string): string[] {
  const stampPath = join(dbDir, "src/generated", STAMP_FILE)
  const stampLabel = label(`src/generated/${STAMP_FILE}`)

  if (!existsSync(stampPath)) {
    return [`${stampLabel} is missing.`]
  }

  const stamped = readFileSync(stampPath, "utf8").trim()

  if (stamped !== fingerprint) {
    return [
      `${stampLabel} records ${stamped}, but the Prisma inputs now hash to ${fingerprint}.`,
    ]
  }

  return []
}

export function checkPrismaClientFreshness(
  dbDir: string = DEFAULT_DB_DIR,
  options: { write?: boolean } = {}
): TFreshnessResult {
  const fingerprint = computeFingerprint(dbDir)
  const failures = collectClientFailures(dbDir)

  if (failures.length > 0) {
    return { failures, fingerprint }
  }

  if (options.write) {
    writeFileSync(join(dbDir, "src/generated", STAMP_FILE), `${fingerprint}\n`)

    return { failures: [], fingerprint }
  }

  return { failures: collectStampFailures(dbDir, fingerprint), fingerprint }
}

function parseArgs(argv: string[]): { dbDir: string; write: boolean } {
  const dbDirIndex = argv.indexOf("--db-dir")
  const dbDir =
    dbDirIndex === -1
      ? DEFAULT_DB_DIR
      : (argv[dbDirIndex + 1] ?? DEFAULT_DB_DIR)

  return { dbDir, write: argv.includes("--write") }
}

function main(): void {
  const { dbDir, write } = parseArgs(process.argv.slice(2))
  const result = checkPrismaClientFreshness(dbDir, { write })

  if (result.failures.length > 0) {
    process.stderr.write(
      `Prisma client freshness guard failed:\n${result.failures.map((line) => `- ${line}`).join("\n")}\n\n${REGENERATE_HINT}\n`
    )
    process.exit(1)
  }

  if (write) {
    process.stdout.write(
      `Prisma inputs stamped in ${relative(process.cwd(), join(dbDir, "src/generated", STAMP_FILE))}: ${result.fingerprint}\n`
    )

    return
  }

  process.stdout.write("Prisma client is up to date with its inputs.\n")
}

if (import.meta.main) {
  main()
}
