package cloudflared

import (
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"pupitre.studio/agent/internal/i18n"
	"pupitre.studio/agent/internal/modules"
	"pupitre.studio/agent/internal/modules/exposure/routes"
	"pupitre.studio/agent/internal/registry"
	"pupitre.studio/agent/internal/sys/apt"
	"pupitre.studio/agent/internal/sys/file"
	"pupitre.studio/agent/internal/sys/systemd"
)

const (
	Unit = "cloudflared"
	Pkg  = "cloudflared"

	ConfigDir       = "/etc/cloudflared"
	ConfigPath      = ConfigDir + "/config.yml"
	CredentialsPath = ConfigDir + "/pupitre.json"
	UnitPath        = "/etc/systemd/system/" + Unit + ".service"
	SourcePath      = "/etc/apt/sources.list.d/cloudflared.list"

	KeyringPath = "/usr/share/keyrings/cloudflare-main.gpg"
	SourceLine  = "deb [signed-by=" + KeyringPath + "] https://pkg.cloudflare.com/cloudflared any main\n"

	keyURL = "https://pkg.cloudflare.com/cloudflare-main.gpg"
)

// Covers the edge's minute-plus propagation of a new tunnel, yet stays under the agent's 3-minute systemctl wait.
const startSeconds = 150

var UnitFile = []byte(`[Unit]
Description=Cloudflare Tunnel (Pupitre)
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
ExecStart=/usr/bin/cloudflared --no-autoupdate --config ` + ConfigPath + ` tunnel run
Restart=always
RestartSec=5
TimeoutStartSec=` + strconv.Itoa(startSeconds) + `

[Install]
WantedBy=multi-user.target
`)

type Credentials struct {
	AccountTag   string `json:"AccountTag"`
	TunnelID     string `json:"TunnelID"`
	TunnelSecret string `json:"TunnelSecret"`
}

func (c Credentials) Encode() []byte {
	content, _ := json.Marshal(c)

	return append(content, '\n')
}

func Recorded(ctx *modules.Context) Credentials {
	raw, err := file.Read(ctx, CredentialsPath)
	if err != nil {
		return Credentials{}
	}

	var found Credentials
	if err := json.Unmarshal(raw, &found); err != nil {
		return Credentials{}
	}

	return found
}

const unknownTunnel = "Tunnel not found"

const registered = "Registered tunnel connection"

// A retry cycle is about a dozen lines; several cycles hold the answer whatever the connection was doing.
const verifiedLines = 60

const keptSaidLines = 2

// systemctl only says the job failed; the daemon's own journal says why.
func StartFailure(ctx *modules.Context, err error) error {
	said := systemd.Diagnose(ctx, Unit)

	if strings.Contains(said, unknownTunnel) {
		return errors.New(i18n.T("modules.cloudflared.start_failed", err.Error(), i18n.T("cloudflared.tunnel.unknown")))
	}

	if said == "" {
		return err
	}

	return errors.New(i18n.T("modules.cloudflared.start_failed", err.Error(), said))
}

// A notify unit goes active only once a connection registered, so only an inactive one is judged on its journal.
func Registered(ctx *modules.Context) error {
	if systemd.Active(ctx, Unit) {
		return nil
	}

	said := systemd.Recent(ctx, Unit, verifiedLines)

	refused := strings.LastIndex(said, unknownTunnel)
	if refused < 0 {
		return nil
	}

	// A new tunnel's first attempts can reach an edge not yet told about it; a later registration outweighs them.
	if strings.LastIndex(said, registered) > refused {
		return nil
	}

	return errors.New(i18n.T("cloudflared.tunnel.unknown"))
}

// Only a warning, never a verdict: a slow link gets there seconds later, and failing would refuse an install that worked.
func Serving(ctx *modules.Context) (bool, string) {
	said := systemd.Recent(ctx, Unit, verifiedLines)

	if strings.Contains(said, registered) || systemd.Active(ctx, Unit) {
		return true, ""
	}

	return false, lastSaid(said)
}

func lastSaid(said string) string {
	lines := strings.Split(said, " / ")

	if len(lines) > keptSaidLines {
		lines = lines[len(lines)-keptSaidLines:]
	}

	return strings.Join(lines, " / ")
}

func Installed(ctx *modules.Context) bool {
	return apt.Installed(ctx, Pkg)
}

func Version(ctx *modules.Context) (string, error) {
	return apt.Version(ctx, Pkg)
}

func Install(ctx *modules.Context) error {
	if err := addRepository(ctx); err != nil {
		return err
	}

	return apt.Install(ctx, Pkg)
}

func addRepository(ctx *modules.Context) error {
	if !file.Exists(ctx, KeyringPath) {
		if err := apt.DearmorKey(ctx, keyURL, KeyringPath); err != nil {
			return err
		}
	}

	if !file.Same(ctx, SourcePath, []byte(SourceLine)) {
		if err := file.WriteAtomic(ctx, SourcePath, []byte(SourceLine), 0o644); err != nil {
			return err
		}
	}

	return apt.RefreshAdded(ctx, SourcePath, KeyringPath)
}

func WriteCredentials(ctx *modules.Context, content Credentials) error {
	if err := ctx.Sys().MkdirAll(ConfigDir, 0o755); err != nil {
		return err
	}

	return file.WriteAtomic(ctx, CredentialsPath, content.Encode(), 0o600)
}

// Rewriting Host defeats a dev server's allowedHosts check without touching its vite.config.ts.
func Ingress(tunnelID string, published []routes.Route) []byte {
	var out strings.Builder

	fmt.Fprintf(&out, "# Generated by pupitred — source: %s\n", registry.DefaultConf)
	fmt.Fprintf(&out, "tunnel: %s\n", tunnelID)
	fmt.Fprintf(&out, "credentials-file: %s\n", CredentialsPath)
	out.WriteString("originRequest:\n  connectTimeout: 30s\ningress:\n")

	for _, route := range published {
		origin := strings.TrimPrefix(route.Service, "http://")

		fmt.Fprintf(&out, "  # %s\n", route.Project)
		fmt.Fprintf(&out, "  - hostname: %s\n", route.Hostname)
		fmt.Fprintf(&out, "    service: %s\n", route.Service)
		out.WriteString("    originRequest:\n")
		fmt.Fprintf(&out, "      httpHostHeader: %s\n", origin)
	}

	out.WriteString("  - service: http_status:404\n")

	return []byte(out.String())
}
